travis:
  secure:
    BINSTAR_TOKEN: TWuXvt97fXo+bBX8+E3k+3PpIdLUgBQxfK1ZN9AkTH2GiNl886UqJnd6phzwg/9RtpQBtUYN1QK7cN8MaEzQAKzVQg6rZHGqkUl8iDEeCNsKkWwAaRiSjOvrGWF8bYFHx3AhjF8A4bxo/b/39f95eMGpoQdM3PgwfN87vWVUr+vaAoeAs4VRS27f2UzVXc5xnW17yPH5Eqyjnt2jy3uIBkSNmzXHL0Z92r84Y1qfrfh5V6eoWAyJDnNYOAtzVanjbIDsFlIrb4EWpRw0id9fJjH4PnZMMZtFma5TYAJUcOvriBw+UVAX17gaDEos0yrnzRIUQ5TjsZ0jYCpKPi4jKmkc9Ji+6fiQOxAFPNUSr7DZWMJIlmtfIN9XinEej3ksQgfKpPDobUPrvr8yuUNPrO642oqsHK0b6k9rcjDXy57nsp7Z99gs8Jzsx1dZBBanU825NtCj+gMNCzKBnLWGU3V6+QPwcsmqKA2gXHMfvEIJaPqpMfOxMquYqm85hotFAJwhWA59R59wglaD8JRV3Pdn+UIErfzj97Auwj8C/H71Umi9FteZa15liu0OFxpxQiVe4QlWRD/rPRXU5ksnaAxdcL+y4Bvg1yv97QDjxJF/V2u4luyhzhjRMTLS7Vh+PXv4psB1/kNH6r/01pHGclNyBaqg/c1hF50WxP9cqfw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
